    save_best: False
    plot_agents: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./dqn_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 4
      nb_seeds: 2
      epsilon_init: 0.02
      max_grad_norm: 0.5
      buffer_size: 1e5
      n_envs: 10
      batch_size: 1024
      nb_measures: 60
      eval_interval: 50000
      target_critic_update: 5000
      nb_evals: 1
      gae: 0.8
      max_epochs: 1000
      discount_factor: 0.99
      architecture:
        hidden_size: [256, 256]

    goal:
      goal_dim: 1
      goal_range: [[-1,1]]
      goal_type: float

    gym_env:
      classname: __main__.make_gym_env
      env_name: CartPole-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 2.3e-3
